# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: false
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Cetmix
org_slug: Cetmix
rebel_module_groups: []
repo_description: Test Task - Packed Picking
repo_name: Packed Picking
repo_slug: test_task_packed_picking
repo_website: https://github.com/dmitriypaulov/test_task_packed_picking
use_pyproject_toml: true
use_ruff: true

